# Generated by Django 5.0.6 on 2024-05-24 14:16

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890', length=7, max_length=7, prefix='', primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
            ],
        ),
    ]
